version: '3.1'
services:
  db:
    image: postgres
    restart: always 
    image: postgres:10.3
    ports: 
      - 5436:5432
    environment:
      POSTGRES_USER: justgo-admin
      POSTGRES_PASSWORD: kidyhpkidyhp
      POSTGRES_DB: justgo

  server:
    ports:
      - 3333:3333   
  client:
    ports:
      - 3002:3002   
